version: '3.1'
services:
  apex:
    build:
      context: ./apex
      dockerfile: ./Dockerfile
    depends_on:
      - orders
     
    ports:
      - '3002:3002'  
  orders:
    build:
      context: ./apexServer
      dockerfile: ./apps/orders/Dockerfile    
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
      - billing
      - auth
      - rabbitmq
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    ports:
      - '3000:3000'
  billing:
    build:
      context: ./apexServer
      dockerfile: ./apps/billing/Dockerfile
      
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
      - rabbitmq
      - auth
    ports:
      - '5000:5000'  
    # volumes:
    #   - .:/app
    #   - /app/node_modules
  auth:
    build:
      context: ./apexServer
      dockerfile: ./apps/auth/Dockerfile     
    ports:
      - '3001:3001'
    
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
      - rabbitmq
    # volumes:
    #   - .:/app
    #   - /app/node_modules
  rabbitmq:
    image: rabbitmq
    # ports:
    #   - '5672:5672'
  mongodb-primary:
    image: docker.io/bitnami/mongodb:5.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    # ports:
    #   - '27017:27017'

  mongodb-secondary:
    image: docker.io/bitnami/mongodb:5.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: docker.io/bitnami/mongodb:5.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongodb_master_data:
    driver: local
